/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package telas;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author zion
 */
public class PainelTabelaBaralhosDoGrupo extends javax.swing.JPanel {

    /**
     * Creates new form PainelTabelaCartas
     */
    public PainelTabelaBaralhosDoGrupo() {
        initComponents();
    }
    public void initEvent(TableActionEvent event, int linha) {
        jogarButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                event.jogar(linha);
            }
        });
        verCartasButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                event.verCards(linha);
            }
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        verCartasButton = new javax.swing.JButton();
        jogarButton = new javax.swing.JButton();

        verCartasButton.setBackground(new java.awt.Color(28, 181, 196));
        verCartasButton.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        verCartasButton.setForeground(new java.awt.Color(255, 255, 255));
        verCartasButton.setText("Ver");
        verCartasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verCartasButtonActionPerformed(evt);
            }
        });

        jogarButton.setBackground(new java.awt.Color(237, 30, 82));
        jogarButton.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jogarButton.setForeground(new java.awt.Color(255, 255, 255));
        jogarButton.setText("Jogar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(verCartasButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jogarButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(verCartasButton)
                    .addComponent(jogarButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void verCartasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verCartasButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_verCartasButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jogarButton;
    private javax.swing.JButton verCartasButton;
    // End of variables declaration//GEN-END:variables
}
