/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package telas;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author zion
 */
public class PainelTabelaBaralhos extends javax.swing.JPanel {

    /**
     * Creates new form PainelTabelaBaralhos
     */
    public PainelTabelaBaralhos() {
        initComponents();

    }

    public void initEvent(TableActionEvent event, int row) {
        excluirBaralhoButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                event.deletarBaralho(row);
            }
        });
        editarBaralhoButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                event.verBaralho(row);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        editarBaralhoButton = new javax.swing.JButton();
        excluirBaralhoButton = new javax.swing.JButton();

        editarBaralhoButton.setBackground(new java.awt.Color(0, 0, 0));
        editarBaralhoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src.main.resources/Imagens/editarBotao_1.png"))); // NOI18N
        editarBaralhoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarBaralhoButtonActionPerformed(evt);
            }
        });

        excluirBaralhoButton.setBackground(new java.awt.Color(237, 30, 82));
        excluirBaralhoButton.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        excluirBaralhoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src.main.resources/Imagens/excluirBotao.png"))); // NOI18N
        excluirBaralhoButton.setMaximumSize(new java.awt.Dimension(30, 30));
        excluirBaralhoButton.setMinimumSize(new java.awt.Dimension(30, 30));
        excluirBaralhoButton.setPreferredSize(new java.awt.Dimension(30, 30));
        excluirBaralhoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirBaralhoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(editarBaralhoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(excluirBaralhoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editarBaralhoButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(excluirBaralhoButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void editarBaralhoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarBaralhoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editarBaralhoButtonActionPerformed

    private void excluirBaralhoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirBaralhoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_excluirBaralhoButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton editarBaralhoButton;
    private javax.swing.JButton excluirBaralhoButton;
    // End of variables declaration//GEN-END:variables
}
