/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package telas;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author zion
 */
public class PainelTabelaGrupos extends javax.swing.JPanel {

    /**
     * Creates new form PainelTabelaGrupos
     */
    public PainelTabelaGrupos() {
        initComponents();
    }
      public void initEvent(TableActionEvent event, int linha) {
        verAlunosGrupoButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                event.verAlunos(linha);
            }
        });
        verBaralhoGrupoButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                event.verBaralhos(linha);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        verBaralhoGrupoButton = new javax.swing.JButton();
        verAlunosGrupoButton = new javax.swing.JButton();

        verBaralhoGrupoButton.setBackground(new java.awt.Color(28, 181, 196));
        verBaralhoGrupoButton.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        verBaralhoGrupoButton.setForeground(new java.awt.Color(255, 255, 255));
        verBaralhoGrupoButton.setText("Baralhos");
        verBaralhoGrupoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verBaralhoGrupoButtonActionPerformed(evt);
            }
        });

        verAlunosGrupoButton.setBackground(new java.awt.Color(237, 30, 82));
        verAlunosGrupoButton.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        verAlunosGrupoButton.setForeground(new java.awt.Color(255, 255, 255));
        verAlunosGrupoButton.setText("Alunos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(verBaralhoGrupoButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(verAlunosGrupoButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(verBaralhoGrupoButton)
                    .addComponent(verAlunosGrupoButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void verBaralhoGrupoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verBaralhoGrupoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_verBaralhoGrupoButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton verAlunosGrupoButton;
    private javax.swing.JButton verBaralhoGrupoButton;
    // End of variables declaration//GEN-END:variables
}

// teste