/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.mavenproject1;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author zion
 */
public class NewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    private Baralho baralho;
    private List<Baralho> listaDeBaralhos;
    private JPanel painelPai;
        public NewJPanel(Baralho baralho, List<Baralho> listaDeBaralhos, JPanel painelPai) {
        this.baralho = baralho;
        this.listaDeBaralhos = listaDeBaralhos;
        this.painelPai = painelPai;

        initComponents();

        // Configurando os valores dos labels
        nomeBaralho.setText("Nome: " + baralho.nome);
        materiaBaralho.setText("Matéria: " + baralho.materia);

        // Adicionando ação ao botão Excluir
        excluir.addActionListener(e -> {
            listaDeBaralhos.remove(baralho); // Remove o baralho da lista
            painelPai.remove(this); // Remove este painel do painel pai
            painelPai.revalidate(); // Revalida o layout do painel pai
            painelPai.repaint(); // Re-pinta para refletir as mudanças
        });

        // Adicionando ação ao botão Editar (para fins de exemplo, apenas exibe uma mensagem)
        editar.addActionListener(e -> {
            JOptionPane.showMessageDialog(this, "Função Editar ainda não implementada.");
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        editar = new javax.swing.JButton();
        excluir = new javax.swing.JButton();
        materiaBaralho = new javax.swing.JLabel();
        nomeBaralho = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        editar.setText("jButton1");
        add(editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 105, -1, -1));

        excluir.setText("jButton2");
        add(excluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 158, -1, -1));

        materiaBaralho.setText("jLabel1");
        add(materiaBaralho, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 24, -1, -1));

        nomeBaralho.setText("jLabel2");
        add(nomeBaralho, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 71, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/analysis.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 4, 390, 290));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton editar;
    private javax.swing.JButton excluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel materiaBaralho;
    private javax.swing.JLabel nomeBaralho;
    // End of variables declaration//GEN-END:variables
}
