/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.lippi.flashcards.pi.telas;

import br.lippi.flashcards.pi.modelo.Usuario;
import br.lippi.flashcards.pi.persistencia.UsuarioDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author Gabriel
 */
public class AutenticarContaTela extends javax.swing.JFrame {

    /**
     * Creates new form AutenticarContaTela
     */
    public AutenticarContaTela() {
        initComponents();
        criarContaPainel.setVisible(false);
        redirecionarTelaCriarContaButton.setContentAreaFilled(false);
        redirecionarTelaAlterarSenhaButton.setContentAreaFilled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        criarContaPainel = new javax.swing.JPanel();
        emailLabel = new javax.swing.JLabel();
        campoEmailTextField = new javax.swing.JTextField();
        senhaLabel = new javax.swing.JLabel();
        campoSenhaPasswordField = new javax.swing.JPasswordField();
        usuarioLabel = new javax.swing.JLabel();
        confirmarSenhaLabel = new javax.swing.JLabel();
        criarContaButton = new javax.swing.JButton();
        campoUsuarioTextField = new javax.swing.JTextField();
        campoConfirmarSenhaPasswordField = new javax.swing.JPasswordField();
        jaTenhoContaLabel = new javax.swing.JLabel();
        autenticarContaPainel = new javax.swing.JPanel();
        EmailLabel = new javax.swing.JLabel();
        campoEmailAutenticarTextField = new javax.swing.JTextField();
        SenhaLabel = new javax.swing.JLabel();
        EntrarButton = new javax.swing.JButton();
        campoSenhaAutenticarPasswordField = new javax.swing.JPasswordField();
        redirecionarTelaAlterarSenhaButton = new javax.swing.JButton();
        redirecionarTelaCriarContaButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Autenticação de Conta");

        emailLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        emailLabel.setText("E-mail");

        campoEmailTextField.setBackground(new java.awt.Color(28, 181, 196));
        campoEmailTextField.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N

        senhaLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        senhaLabel.setText("Senha");

        campoSenhaPasswordField.setBackground(new java.awt.Color(28, 181, 196));
        campoSenhaPasswordField.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N

        usuarioLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        usuarioLabel.setText("Usuário");

        confirmarSenhaLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        confirmarSenhaLabel.setText("Confirmar senha");

        criarContaButton.setBackground(new java.awt.Color(237, 30, 82));
        criarContaButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        criarContaButton.setForeground(new java.awt.Color(255, 255, 255));
        criarContaButton.setText("Criar conta");
        criarContaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criarContaButtonActionPerformed(evt);
            }
        });

        campoUsuarioTextField.setBackground(new java.awt.Color(28, 181, 196));
        campoUsuarioTextField.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N

        campoConfirmarSenhaPasswordField.setBackground(new java.awt.Color(28, 181, 196));
        campoConfirmarSenhaPasswordField.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N

        jaTenhoContaLabel.setForeground(new java.awt.Color(28, 181, 196));
        jaTenhoContaLabel.setText("Já tenho conta");

        javax.swing.GroupLayout criarContaPainelLayout = new javax.swing.GroupLayout(criarContaPainel);
        criarContaPainel.setLayout(criarContaPainelLayout);
        criarContaPainelLayout.setHorizontalGroup(
            criarContaPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(criarContaPainelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(criarContaPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(emailLabel)
                    .addComponent(senhaLabel)
                    .addComponent(campoEmailTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                    .addComponent(campoSenhaPasswordField))
                .addGroup(criarContaPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(criarContaPainelLayout.createSequentialGroup()
                        .addGroup(criarContaPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(criarContaPainelLayout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(usuarioLabel)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, criarContaPainelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(criarContaPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(confirmarSenhaLabel)
                                    .addComponent(campoConfirmarSenhaPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(criarContaPainelLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(campoUsuarioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(criarContaPainelLayout.createSequentialGroup()
                .addGroup(criarContaPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(criarContaPainelLayout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(criarContaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(criarContaPainelLayout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(jaTenhoContaLabel)))
                .addContainerGap(180, Short.MAX_VALUE))
        );
        criarContaPainelLayout.setVerticalGroup(
            criarContaPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(criarContaPainelLayout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addGroup(criarContaPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel)
                    .addComponent(usuarioLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(criarContaPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoEmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoUsuarioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(criarContaPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(senhaLabel)
                    .addComponent(confirmarSenhaLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(criarContaPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoSenhaPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoConfirmarSenhaPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addComponent(jaTenhoContaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(criarContaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        EmailLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        EmailLabel.setText("E-mail");

        campoEmailAutenticarTextField.setBackground(new java.awt.Color(28, 181, 196));
        campoEmailAutenticarTextField.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        campoEmailAutenticarTextField.setForeground(new java.awt.Color(255, 255, 255));
        campoEmailAutenticarTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        SenhaLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        SenhaLabel.setText("Senha");

        EntrarButton.setBackground(new java.awt.Color(237, 30, 82));
        EntrarButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        EntrarButton.setForeground(new java.awt.Color(255, 255, 255));
        EntrarButton.setText("Entrar");
        EntrarButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EntrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntrarButtonActionPerformed(evt);
            }
        });

        campoSenhaAutenticarPasswordField.setBackground(new java.awt.Color(28, 181, 196));
        campoSenhaAutenticarPasswordField.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N

        redirecionarTelaAlterarSenhaButton.setBackground(new java.awt.Color(60, 63, 65));
        redirecionarTelaAlterarSenhaButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        redirecionarTelaAlterarSenhaButton.setForeground(new java.awt.Color(28, 181, 196));
        redirecionarTelaAlterarSenhaButton.setText("Alterar Senha");
        redirecionarTelaAlterarSenhaButton.setBorder(null);
        redirecionarTelaAlterarSenhaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redirecionarTelaAlterarSenhaButtonActionPerformed(evt);
            }
        });

        redirecionarTelaCriarContaButton.setBackground(new java.awt.Color(60, 63, 65));
        redirecionarTelaCriarContaButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        redirecionarTelaCriarContaButton.setForeground(new java.awt.Color(28, 181, 196));
        redirecionarTelaCriarContaButton.setText("Criar Conta");
        redirecionarTelaCriarContaButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        redirecionarTelaCriarContaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redirecionarTelaCriarContaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout autenticarContaPainelLayout = new javax.swing.GroupLayout(autenticarContaPainel);
        autenticarContaPainel.setLayout(autenticarContaPainelLayout);
        autenticarContaPainelLayout.setHorizontalGroup(
            autenticarContaPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(autenticarContaPainelLayout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addGroup(autenticarContaPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(autenticarContaPainelLayout.createSequentialGroup()
                        .addComponent(redirecionarTelaAlterarSenhaButton)
                        .addGap(18, 18, 18)
                        .addComponent(redirecionarTelaCriarContaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(autenticarContaPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(SenhaLabel)
                        .addComponent(EmailLabel)
                        .addComponent(campoSenhaAutenticarPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(EntrarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(campoEmailAutenticarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(212, Short.MAX_VALUE))
        );
        autenticarContaPainelLayout.setVerticalGroup(
            autenticarContaPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(autenticarContaPainelLayout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addComponent(EmailLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoEmailAutenticarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(SenhaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoSenhaAutenticarPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addGroup(autenticarContaPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(redirecionarTelaAlterarSenhaButton)
                    .addComponent(redirecionarTelaCriarContaButton))
                .addGap(2, 2, 2)
                .addComponent(EntrarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(autenticarContaPainel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(296, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(168, 168, 168)
                    .addComponent(criarContaPainel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(403, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(autenticarContaPainel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(criarContaPainel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EntrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntrarButtonActionPerformed
try {
            String email = campoEmailAutenticarTextField.getText();
            var pass = campoSenhaAutenticarPasswordField.getPassword();
            String senha = new String(pass);
            Usuario usuario = new Usuario(email, "nomeTeste", senha, "valorFodase");
            var usuarioDAO = new UsuarioDAO();
            boolean confirmar = usuarioDAO.autenticar(usuario);
            if (confirmar){
            JOptionPane.showMessageDialog(null, "Deu certo!");
            }
            else{
               JOptionPane.showMessageDialog(null, "Deu nao encontrado!"); 
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Tente novamente mais tarde!");
        }
    }//GEN-LAST:event_EntrarButtonActionPerformed

    private void criarContaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criarContaButtonActionPerformed
        // TODO add your handling code here:
        try {
            String email = campoEmailTextField.getText();
            String nomeUsuario = campoUsuarioTextField.getText();
            var pass = campoSenhaPasswordField.getPassword();
            String senha = new String(pass);
            var usuario = new Usuario(email, nomeUsuario, senha, "professor");
            var usuarioDAO = new UsuarioDAO();
            usuarioDAO.cadastrar(usuario);
            JOptionPane.showMessageDialog(null, "Deu certo!");
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Tente novamente mais tarde!");
        }
    }//GEN-LAST:event_criarContaButtonActionPerformed

    private void redirecionarTelaAlterarSenhaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redirecionarTelaAlterarSenhaButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_redirecionarTelaAlterarSenhaButtonActionPerformed

    private void redirecionarTelaCriarContaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redirecionarTelaCriarContaButtonActionPerformed
        autenticarContaPainel.setVisible(false);
        criarContaPainel.setVisible(true);
    }//GEN-LAST:event_redirecionarTelaCriarContaButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AutenticarContaTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AutenticarContaTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AutenticarContaTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AutenticarContaTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AutenticarContaTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JButton EntrarButton;
    private javax.swing.JLabel SenhaLabel;
    private javax.swing.JPanel autenticarContaPainel;
    private javax.swing.JPasswordField campoConfirmarSenhaPasswordField;
    private javax.swing.JTextField campoEmailAutenticarTextField;
    private javax.swing.JTextField campoEmailTextField;
    private javax.swing.JPasswordField campoSenhaAutenticarPasswordField;
    private javax.swing.JPasswordField campoSenhaPasswordField;
    private javax.swing.JTextField campoUsuarioTextField;
    private javax.swing.JLabel confirmarSenhaLabel;
    private javax.swing.JButton criarContaButton;
    private javax.swing.JPanel criarContaPainel;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel jaTenhoContaLabel;
    private javax.swing.JButton redirecionarTelaAlterarSenhaButton;
    private javax.swing.JButton redirecionarTelaCriarContaButton;
    private javax.swing.JLabel senhaLabel;
    private javax.swing.JLabel usuarioLabel;
    // End of variables declaration//GEN-END:variables
}
